---
site:
  title: OpenShift Observability Workshop
  url: https://cldmnky.github.io/observability-workshop/modules/index.html
  start_page: modules::index.adoc

content:
  sources:
    - url: /showroom/repo
      start_path: showroom/content

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    release-version: master
  extensions:
    - ./content/lib/tab-block.js
    - ./content/lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/showroom-template/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: ./content/lib
    - path: partials/footer-scripts.hbs
      contents: |
        <script defer src="{{uiRootPath}}/js/vendor/clipboard.js"></script>
        <script defer src="{{uiRootPath}}/js/site.js"></script>
        <script defer src="{{uiRootPath}}/js/vendor/highlight.js"></script>
        <script defer src="{{uiRootPath}}/js/user-context.js"></script>
    - path: img/favicon.ico
      src: ./content/supplemental-ui/img/favicon.ico
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

runtime:
  cache_dir: ./.cache/antora

antora:
  extensions:
    - require: ./content/lib/compute-attributes.js
    - require: ./content/lib/mermaid-block.js
      enabled: false

output:
  dir: ./www
