apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  namespace: __NAMESPACE__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: frontend-build
  namespace: __NAMESPACE__
spec:
  source:
    type: Git
    git:
      url: https://github.com/cldmnky/observability-workshop.git
      revision: main
    contextDir: src
  strategy:
    kind: ClusterBuildStrategy
    name: buildah
  paramValues:
    - name: dockerfile
      value: frontend/Containerfile
  output:
    image: image-registry.openshift-image-registry.svc:5000/__NAMESPACE__/frontend:latest
  serviceAccount: builder
---
apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: backend-build
  namespace: __NAMESPACE__
spec:
  source:
    type: Git
    git:
      url: https://github.com/cldmnky/observability-workshop.git
      revision: main
    contextDir: src
  strategy:
    kind: ClusterBuildStrategy
    name: buildah
  paramValues:
    - name: dockerfile
      value: backend/Containerfile
  output:
    image: image-registry.openshift-image-registry.svc:5000/__NAMESPACE__/backend:latest
  serviceAccount: builder
---
apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: database-build
  namespace: __NAMESPACE__
spec:
  source:
    type: Git
    git:
      url: https://github.com/cldmnky/observability-workshop.git
      revision: main
    contextDir: src
  strategy:
    kind: ClusterBuildStrategy
    name: buildah
  paramValues:
    - name: dockerfile
      value: database/Containerfile
  output:
    image: image-registry.openshift-image-registry.svc:5000/__NAMESPACE__/database:latest
  serviceAccount: builder
---
apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: notifier-build
  namespace: __NAMESPACE__
spec:
  source:
    type: Git
    git:
      url: https://github.com/cldmnky/observability-workshop.git
      revision: main
    contextDir: src/notifier
  strategy:
    kind: ClusterBuildStrategy
    name: buildah
  paramValues:
    - name: dockerfile
      value: Containerfile
  output:
    image: image-registry.openshift-image-registry.svc:5000/__NAMESPACE__/notifier:latest
  serviceAccount: builder
---
apiVersion: shipwright.io/v1beta1
kind: BuildRun
metadata:
  name: frontend-buildrun
  namespace: __NAMESPACE__
spec:
  build:
    name: frontend-build
---
apiVersion: shipwright.io/v1beta1
kind: BuildRun
metadata:
  name: backend-buildrun
  namespace: __NAMESPACE__
spec:
  build:
    name: backend-build
---
apiVersion: shipwright.io/v1beta1
kind: BuildRun
metadata:
  name: database-buildrun
  namespace: __NAMESPACE__
spec:
  build:
    name: database-build
---
apiVersion: shipwright.io/v1beta1
kind: BuildRun
metadata:
  name: notifier-buildrun
  namespace: __NAMESPACE__
spec:
  build:
    name: notifier-build
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: __NAMESPACE__
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: image-registry.openshift-image-registry.svc:5000/__NAMESPACE__/frontend:latest
          imagePullPolicy: Always
          env:
            - name: FRONTEND_ADDR
              value: :8080
            - name: BACKEND_URL
              value: http://backend:8081
            - name: SERVICE_NAME
              value: frontend
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: __NAMESPACE__
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: image-registry.openshift-image-registry.svc:5000/__NAMESPACE__/backend:latest
          imagePullPolicy: Always
          env:
            - name: BACKEND_ADDR
              value: :8081
            - name: DATABASE_API_URL
              value: http://database:8082
            - name: NOTIFIER_URL
              value: http://notifier:8083
            - name: SERVICE_NAME
              value: backend
          ports:
            - containerPort: 8081
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: __NAMESPACE__
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: image-registry.openshift-image-registry.svc:5000/__NAMESPACE__/database:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_ADDR
              value: :8082
            - name: DATABASE_FILE
              value: /var/lib/chai/eventsdb
            - name: SERVICE_NAME
              value: database
          ports:
            - containerPort: 8082
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 384Mi
          volumeMounts:
            - mountPath: /var/lib/chai
              name: database-storage
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-data
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: __NAMESPACE__
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: frontend
  namespace: __NAMESPACE__
  labels:
    app: frontend
spec:
  to:
    kind: Service
    name: frontend
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: __NAMESPACE__
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8081
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: __NAMESPACE__
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
    - name: http
      port: 8082
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: __NAMESPACE__
  labels:
    app: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
      # OpenTelemetry auto-instrumentation is intentionally NOT enabled here.
      # Students add the sidecar + instrumentation annotations in Module 4 as
      # a hands-on exercise demonstrating zero-code Python instrumentation.
    spec:
      containers:
        - name: notifier
          image: image-registry.openshift-image-registry.svc:5000/__NAMESPACE__/notifier:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_API_URL
              value: http://database:8082
            - name: SERVICE_NAME
              value: notifier
          ports:
            - containerPort: 8083
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: notifier
  namespace: __NAMESPACE__
  labels:
    app: notifier
spec:
  selector:
    app: notifier
  ports:
    - name: http
      port: 8083
      targetPort: http
